version: '3.7'

services:
  web:
    container_name: bookbnb-payment_web

    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

    ports:
      - 5000:8080 # host=4000 --> docker=8080

    depends_on:
      - db # first execute database
      - sc # and execute smart contract

    environment:
      ENVIRONMENT: ${ENVIRONMENT:-development}
      DATABASE_URL: sqlite:///./app.db

      # just local testing
      URL_NODE: http://sc:8545

    networks:
      - payments-net


  db:
    container_name: bookbnb-payment_db

    image: postgres:12.1-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=payment
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_db_dev

    networks:
      - payments-net


  sc:
    container_name: bookbnb-payment_sc

    image: trufflesuite/ganache-cli:latest

    ports:
      - 8545:8545

    command: -e 1000000 -s asecretseed

    networks:
      - payments-net

volumes:
  node_modules:
  postgres_data:

networks:
  payments-net: